name: Build and Deploy Android App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 14

      - name: Build and assemble app
        run: ./gradlew assembleFreeVersionDebug

      - name: Upload to App Center
        uses: microsoft/appcenter-upload-action@v1
        with:
          app-file: app/build/outputs/apk/debug/app-freeVersion-debug.apk
          app-name: GithubActionSample
          api-token: bde6bfca8fceca8932a1bd64f0eeb8eebff9ec46
