name: Fetch json value
on:
  workflow_dispatch:

jobs:
  build:
    name: Fetch json value
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Set environment variable
        run: echo "FIREBASE_AUTH_KEY=${{ secrets.FIREBASE_KEY }}" >> $GITHUB_ENV

      - name: Run javascript file
        run: node .github/workflows/abc.js