name: Build and Sign APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Find JKS File
        run: |
          JKS_FILE=$(find . -type f -name "*.jks")

          if [ -n "$JKS_FILE" ]; then
            echo "JKS file found: $JKS_FILE"
          else
            echo "JKS file not found."
            exit 1
          fi

      - name: Build release APK
        run: ./gradlew assembleFreeVersionRelease

      - name: Sign APK
        run: |
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
            -keystore app/rohit.jks \
            -storepass rohit123 \
            -keypass rohit123 \
            app/build/outputs/apk/freeVersion/release/app-release-unsigned.apk \
            rohit123

      - name: Verify and align APK
        run: |
          zipalign -v 4 \
            app/build/outputs/apk/freeVersion/release/app-release-unsigned.apk \
            app/build/outputs/apk/freeVersion/release/app-release.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: app/build/outputs/apk/freeVersion/release/app-release.apk
