name: Set data from list

on:
  workflow_dispatch:
    inputs:
      option:
        description: "Select an option from the list"
        required: true

jobs:
  fetch_list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set input options
        run: |
          list=("Option1" "Option2" "Option3")
          options=""
          for item in "${list[@]}"
          do
              options+=$item"\n"
          done
          echo "::set-input name=option::$options"
        shell: bash
